name: PHP Composer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-
    - name: Create temporary ssh key
      run: echo "${{ secrets.SSH_PRIVATE_KEY }}" > ssh-key.pem
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      
    - name: Debug file path
      run: echo "Arquivo ssh-key.pem encontrado em:$(pwd)/ssh-key.pem"

    - name: Configure ssh-agent
      run: |
        chmod 600 ssh-key.pem
        eval "$(ssh-agent -s)"
        ssh-add ssh-key.pem
    
    - name: Deploy to server
      run: rsync -avz -e 'ssh -i ssh-key.pem' --delete --exclude='.git' --exclude='vendor' . ubuntu@ec2-18-228-223-214.sa-east-1.compute.amazonaws.com > rsync-output.txt
    - name: Debug file path
      run: echo "encontrado em:$(pwd)"
    - name: Examine rsync output
      run: cat rsync-output.txt
        
    - name: Cleanup ssh key
      run: rm ssh-key.pem
