name: PHP Composer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Set up PEM key
      run: echo ${{ secrets.PEM_KEY }} | tr -d '\r' > teste.pem
      run: chmod 600 teste.pem
      
    - name: Deploy to server
      run: rsync -avz -e "ssh -i teste.pem" --delete --exclude='.git' --exclude='vendor' . ubuntu@ec2-18-231-56-176.sa-east-1.compute.amazonaws.com:/var/www/html/teste_github/teste_github
