name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

env:
  DO_IP: 64.225.52.60

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH
      uses: actions/setup-ssh@v1
      with:
        ssh-key: ${{ secrets.SENHA_ACOCERTO }}

    - name: Deploy to DigitalOcean
      run: |
        ssh root@${{ env.DO_IP }} << EOF
        cd /home
        git pull origin main
        EOF
