name: Push-to-EC2
on:
  push:
    branches:
      - main
env:
  SSH_PRIVATE_KEY: ${{ secrets.SENHA_ACOCERTO }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH
      uses: shogo82148/actions-setup-ssh@v1
      with:
        ssh-private-key: ${{ env.SSH_PRIVATE_KEY }}

    - name: Deploy to DigitalOcean
      uses: appleboy/scp-action@v1
      with:
        host: 64.225.52.60
        username: root
        key: ${{ env.SSH_PRIVATE_KEY }}
        source: .
        target: /var/www/html/github_teste
