name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

env:
  DO_IP: 64.225.52.60

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH key
      run: |
        mkdir ~/.ssh
        echo "${{ secrets.SENHA_ACOCERTO }}" | tr -d '\r' > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ env.DO_IP }} >> ~/.ssh/known_hosts

    - name: Deploy to DigitalOcean
      run: |
        ssh root@${{ env.DO_IP }} << EOF
        cd /path/to/your/project
        git pull origin main
        EOF
