name: Push-to-EC2
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the files
      uses: actions/checkout@v3

    - name: Setup SSH
      uses: azure/setup-ssh@v1
      with:
        ssh-key: ${{ secrets.SENHA_ACOCERTO }}
        
    - name: Deploy to DigitalOcean
      run: |
       ssh root@64.225.52.60 << EOF
       cd /home
       git pull origin main
       EOF
